### ISSUE TITLE
Displaying quotes

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#10]
Mike and I think that quotes could be better presented on the website, as it's not really obvious they are quotes. 

See for example the quote at the top of the page:
http://transitionmovement.org/do-transition/starting-transition/7-essential-ingredients/community-involvement/

Some sites put a colour block around it, or have a line down the side.  Rather than change the design, could we not add a style standard or font change that highlights it is a quote. 
Jay and Ella - do you have any suggestions for a way forward that doesn't involve a CR?

Thanks
Ainslie

(sorry tried to add Mike to this so that he could track this issue but can't work out how to do that!)

**Comment by thisisyoke** [comment]
Hi Guys, you already have a quote style to use. you can create a new flexible content block that is a quote:

![image](https://cloud.githubusercontent.com/assets/4559257/18945708/a6d29bea-8623-11e6-9606-4a97bc04150e.png)

I just created a new quote block on that community involvment page and moved your quote text in:

http://transitionmovement.org/do-transition/starting-transition/7-essential-ingredients/community-involvement/

Looks good to me

**Comment by ainsliebeattie** [comment]
thanks Ella - I thought that we had talked about that before!
