### ISSUE TITLE
Photos/ excerpts in social media

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#103]
Hi I noticed that Twitter/ Facebook don't always fetch an image/ excerpt from the site.

On other sites I use this https://wordpress.org/plugins/wonderm00ns-simple-facebook-open-graph-tags/ to set a default image where the page does not provide one.

What would be your suggested way forward to make sure that all pages show up with an excerpt and image In Twitter/ Facebook?

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

What would be your preferred default image to use if the page does not provide one? I can then get Tom to implement a fallback for if there is no image on the page for Facebook/Twitter to grab.

Many thanks

Ella

**Comment by samuk** [comment]
Hi Ella

That would certainly address part of the issue.

Would it also handle the meta tagging to include an excerpt? 

eg https://twitter.com/transitiontowns/status/803973740035997696

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

Is something like the below what you would like to achieve? (this is an example from another website we manage). Please could you bullet out the requirements, and we can then use that as a brief to identify the best course of action to meet your needs. 

We will also need confirmation of the default image which should appear in the event that there is not an image to pull from the page. (on the site example below they use their logo, but you may want to use the homepage hero illustration for example - let me know what you prefer). 

Many thanks

![screen shot 2016-12-01 at 09 57 28](https://cloud.githubusercontent.com/assets/10939874/20789536/b540093c-b7ac-11e6-8199-843e50ed904d.png)

**Comment by samuk** [comment]
@ainsliebeattie do you have a view on this? I'd say the FB is looking right above, and would be good to have similar meta tags for Twitter?

**Comment by samuk** [comment]
Hi Jay

It would be great if you could get this working on Facebook as above, with Twitter also getting an image and tease.

**Comment by thisisyoke** [comment]
We have Yoast plugin installed, which handles the social info out of the box. It grabs the featured image of the post and uses that. So we are getting the issue where a page or post doesn't have a featured image added Yoast is then struggling to find anything.

What Yoast does is allows you to add one manually via the admin panel. If you go to edit any page or post, you will see the Yoast panel.:

![image](https://cloud.githubusercontent.com/assets/4559257/22019618/322fe2b8-dcac-11e6-92b1-b48ed758caad.png)

You can then click on the social icon to se that panel screenshotted above. this allows you to overide the automatic settings and add your own image.

This is a manual process obviously.

We could look at trying to set a default for all pages and posts without a featured image, but will take up some time in the maintenance. Do you want us to estimate or are you happy to embrace Yoast's manual feature?

thanks

**Comment by arhinostorm** [comment]
I have added a default image for all pages. If there is a featured image it will use this instead. You can also manually override the image using the yoast seo plugin settings when you edit each page / post. 

The default I have set is this:

https://transitionnetwork.org/wp-content/uploads/2016/07/facebook-share.jpg

You can change it by going into SEO menu item on the main wordpress menu on the left hand side. Then go into 'social', then the facebook tab.
