### ISSUE TITLE
Captcha fails on submit new initative

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#104]
"Our group didn't seem to be there, so I tried to Create an Initiative (this seemed the only vaguely relevant option on the dashboard). It keeps giving me an error message on the "I am not a robot" test. I click it, the arrow turns a few times, it changes to a tick - but is apparently invalid when I press Submit."

This is the second report of this I've received

**Comment by yvonnestruthers** [comment]
@arhinostorm please could you look into this - it sounds similar to the issue on the user sign up form

**Comment by samuk** [comment]
I wonder if we even need a captcha here at all? They have already passed it once to complete registration. Presumably if a bot can pass it once, it can also pass it a second time?

**Comment by arhinostorm** [comment]
I have removed for now, whilst we investigate on staging. Seems to be an issue with SSL and recaptcha. The signup form uses a wordpress plugin which we're edited to make work for SSL - this form is a separate code base so needs looking into.

**Comment by yvonnestruthers** [comment]
Hi @samuk @ainsliebeattie 

as per my email, Tom has implemented a fix for this on dev, please could you check it and let me know if you are happy for this to go to live 

http://www.dev.transitionnetwork.org/

Please use the log in details I provided via email for the basic auth. 

For the front end log in please use: 

user: jeff
pw: jeff

and then try to create an initiative

**Comment by samuk** [comment]
Hi Ella

Sorry for the slow reply to this one. Could you double check the user/pass? I don't seem to be able to get in as jeff.

**Comment by yvonnestruthers** [comment]
Hi Sam,

I've just successfully signed in as jeff to the front end - are you able to try again? 

Just to be clear, this is only for the front end where a user signs in (where you have 'log in' in the top bar in blue) 

Many thanks

Ella

**Comment by samuk** [comment]
Ah got it. Could you email me the basic auth details? I don't think I have them..

**Comment by yvonnestruthers** [comment]
Hi Sam,

I have just resent you the email - let me know if it doesn't arrive. 

Many thanks

**Comment by samuk** [comment]
Thanks for password reminder.  I can confirm that the form submission is working for me now.

**Comment by yvonnestruthers** [comment]
No worries - and thanks for the approval. 

@arhinostorm this one can go live. 

Thanks!
