### ISSUE TITLE
Replace wordpress logo with Transition one on wp-login

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#105]
On this page please change the wordpress logo https://transitionnetwork.org/wp-login.php

For a suitably re-sized version of https://transitionnetwork.org/wp-content/uploads/2016/12/Transition-Network-logo6.jpg

Not urgent at all, just adding so we don't forget

**Comment by yvonnestruthers** [comment]
hello @arhinostorm please could you estimate this one? Thanks!

**Comment by arhinostorm** [comment]
10 mins.
