### ISSUE TITLE
Embed login form on https://transitionnetwork.org/transition-near-me/create-an-initiative/

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#106]
For logged out users on this page
https://transitionnetwork.org/transition-near-me/create-an-initiative/

Could we display a login form https://codex.wordpress.org/Function_Reference/wp_login_form
& below that a link to https://transitionnetwork.org/user-register/

Not urgent, but nice to have

**Comment by yvonnestruthers** [comment]
hey @arhinostorm are you able to estimate for this one?

**Comment by arhinostorm** [comment]
After looking into this, I don't think it's possible. We're using the gravity forms register add on which uses a widget for the login form. There is no shortcode for this, and essentially you can only have one of these widgets per page and it's already in the header.

**Comment by yvonnestruthers** [comment]
Thanks Tom - will close the issue in that case.
