### ISSUE TITLE
Dev area broken after application of SSL

### ISSUE THREAD

**Issue by yvonnestruthers** [transitionnetwork/TNv3.0#107]
Hetzner have implemented SSL onto the dev. area, which has broken all images. With live there were issues with the map, and with Recaptcha as well which had to be fixed in line with using SSL - I imagine these issues will be there on dev. too 

@arhinostorm could you take a look and get dev. into a state you'll be happy to test upcoming work on?

**Comment by arhinostorm** [comment]
Done. 20 mins.
