### ISSUE TITLE
Healtcheck form not appearing for logged in subscribers

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#108]
This form
https://transitionnetwork.org/wp-admin/admin.php?page=gf_edit_forms&id=6

Is enabled on this page
https://transitionnetwork.org/do-transition/healthcheck/#healthcheck

When not logged in it prompts for the user to login (see image)

When logged in as subscriber the form is not visible. (I can see the form HTML if I view-source but the form does not render)
![login](https://cloud.githubusercontent.com/assets/400875/21184905/6a3b59fa-c206-11e6-8b6d-5192fa226107.png)

If I log in as my admin user the form is viewable and correct.

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi @arhinostorm are you able to look into this one please?

**Comment by arhinostorm** [comment]
Done. 30 mins
