### ISSUE TITLE
Untitled posts created

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#110]
We have a large number of untitled posts created.

https://transitionnetwork.org/wp-admin/edit.php

I wonder if these are created when users create profiles? Or some other thing?

At least two have been created by users who I know to be legitimate real users.

The only issue with them is it makes it harder for Rob/authors to manage their blog posts in the backend.

**Comment by thisisyoke** [comment]
We will look into this now for you

**Comment by arhinostorm** [comment]
This was gravity forms and the register process creating a draft untitled post with every signup. I've fixed and removed all the untitled posts.
