### ISSUE TITLE
Move RSS feed URL 

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#113]
Hi could you move the RSS feed url 

https://transitionnetwork.org/feed/

To live on the old url
www.transitionnetwork.org/news/feed

We've had feedback that a fair few groups aggregated from the old feed.

Thanks

Sam

**Comment by thisisyoke** [comment]
We have never done this before, and after some quick research this seems to not be a common thing to do. There doesn't seem to be a tried and tested approach as this is baked into wordpress and could cause quite a few complications if we tried to do it via the htaccess.

@samuk What is the possiblity of sending out an email with the new url for RSS feeds to those who use it? Might be a lot quicker/easier.

**Comment by samuk** [comment]
Hi we don't know exactly who is using the URL or what their email addresses might be. We know about a subset of them, but it would be better from a user experience if they didn't have to change. Often sites are set up and then the tech moves on, so it will be beyond the ability of many to update.

I'd suggest leaving the existing feed as it is and simply adding a new feed in addition. A plugin I've used to do this in the past is https://en-gb.wordpress.org/plugins/wp-rss-customizer/

I think there a few that do similar if you're not keen on that one.

Thanks

Sam

**Comment by thisisyoke** [comment]
Hi @samuk 
I will check with tom.. I am just mindful that we don't want to get to a situation where you have to many plugins running on the site that could cause issues. I will see what he thinks and get back to you.

**Comment by thisisyoke** [comment]
Tom is happy to go for installing a plugin, but will look around for a more tried and tested one he thinks..that one only has 50 installs so far. 

Estimate is 30 mins to find, install and test a new plugin. Shall we add this to the next block of maintenance tasks in Jan? I am grouping them together into blocks of 3-4 hours so then Tom can get more done. He closed a few off yesterday fyi

**Comment by samuk** [comment]
Hi Jay, we need to keep time aside to do the migration over to the server, so it would be great if you could hold off any other tickets for now. 

I'm in the process of moving the old site / deleting the old 'transitionnetwork.org' account on our main Hetzner site. As soon as I've done this I'll let you know the FTP details for beanstalk. It's taking a while because there's so much content to move..

**Comment by samuk** [comment]
When we do get to this ticket post-migration, would it be possible to look for a plugin that will also add images to RSS eg https://wordpress.org/plugins/send-images-rss/

It may be possible to find a plugin that does both, or it would be OK to separate the two requirements

1) A RSS on www.transitionnetwork.org/news/feed (may or may not include images)

2) A RSS on www.transitionnetwork.org/feed which includes images so we can syndicate into Mailchimp RSS campaigns.

Thanks

Sam

**Comment by thisisyoke** [comment]
Ok, I think doing the migration may take up all of january's time, but lets see where we get to. 

#109 is the priority then

**Comment by thisisyoke** [comment]
Lets carry on with this one now

**Comment by thisisyoke** [comment]
To confirm, lets do 2 tasks:

1. A RSS on www.transitionnetwork.org/news/feed (may or may not include images)

2. A RSS on www.transitionnetwork.org/feed which includes images so we can syndicate into Mailchimp RSS campaigns. (embrace plugin perhaps)

**Comment by arhinostorm** [comment]
Images have been added to /feed url. Setting up a custom url at an address that does not begin with /feed is proving to be very tricky and starting to eat a lot of time. I've tried a few plugins, and writing some custom code in functions but no joy...

One simpler solution is just setting up a 301 redirect to /feed/news redirects them to /feed. Is that an acceptable solution?

**Comment by samuk** [comment]
A 301 would be better than nothing. Could you add, please.
