### ISSUE TITLE
Site access issue - URGENT

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#114]
Email from Rob this morning - "

 I can't get on the TN site...  I get this... help!

Your connection is not private

Attackers might be trying to steal your information from transitionnetwork.org (for example, passwords, messages or credit cards). NET::ERR_CERT_DATE_INVALID
 
Automatically report details of possible security incidents to Google. Privacy Policy
Back to safetyHIDE ADVANCED
This server could not prove that it is transitionnetwork.org; its security certificate expired yesterday. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Monday, 23 January 2017. Does that look right? If not, you should correct your system's clock and then refresh this page. Find out more.

**Comment by thisisyoke** [comment]
This looks like something has changed with the SSL cetificate. @samuk have you made any changes to your hosting?

**Comment by thisisyoke** [comment]
These are the main reasons are one of the following:

- it isn't signed by one of the root CA certificates that the browser implicitly trusts
- it's signed by a root CA certificate that the browser used to trust, but doesn't any more because - - the CA turned out to a rogue
- the certificate has expired
- the certificate has been revoked by its creator
- the certificate says it is for another site, not the site you're looking at

**Comment by ainsliebeattie** [comment]
Thanks - I am a bit stuck as sam is not working today -I am trying to get
hold of him but I don't really know what to do....


Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb

**Comment by thisisyoke** [comment]
To be honest we had nothing to do with wither the purchasing and then configuring of the ssl certificate so we have no info on how to make any changes, I am sorry.

All I can think is that something has been changed over the weekend, but I can not be sure what. Sorry it is vague. 

Can you get Sam on his mobile?

**Comment by ainsliebeattie** [comment]
Yep - totally understand it is in my court.  Only thing I don't have is
access to Hetzner -the host.  I know there was nothing changed by us but
Sam did do some updating thursday - can't see how that happens to affect
things today. Sam not answering - so I am working on it.  Just wondering -
Ella had access and details to contact Hetzner - I could use those if you
have access to them in the project file?

Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb

**Comment by thisisyoke** [comment]
The only info I can find is a login to this area:

https://konsoleh.your-server.de/frameset_home.php

which is a control panel of sorts, but it is for the transitionmovement.org domain. I dont think that will help unfortunately. I will check with tom

**Comment by thisisyoke** [comment]
think this is it:

New server logins: URL: https://konsoleh.your-server.de/?domain=transitionnetwork.org
Login: transitionnetwork.org
konsoleh.your-server.de
konsoleH ::  Anmeldung
konsoleH ist eine Entwicklung der Hetzner Online GmbH

will send you the passoword in an email

**Comment by ainsliebeattie** [comment]
thanks so much.

looks like ssl has expired...trying to work out how to get it redone and
who it was through. Hetzner said it can take a day. ho hum!


Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb

**Comment by thisisyoke** [comment]
ooops, best of luck

**Comment by ainsliebeattie** [comment]
Thanks for all your help - all fixed.
