### ISSUE TITLE
User role editor

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#115]
Hi I'd like to be able to grant a member of staff permission to edit users, Ideally without granting full admin access.

I'd be inclined to use 
https://wordpress.org/plugins/user-role-editor/

Or you may want to create a custom role with these capabilities?

Thanks

Sam

**Comment by thisisyoke** [comment]
Hi @samuk What role do they currently have?

**Comment by samuk** [comment]
Hi @thisisyoke they are currently editors. Thanks Sam

**Comment by samuk** [comment]
Hi I've spotted user role editor has appeared on the site. Thanks for this. Is it OK if I start using the functionality? 

I'd add a role 'initiative editor' with permissions to
create_users
edit_users
edit_others_initiative_profiles

Or do you want to do further testing first?

Thanks

Sam

**Comment by arhinostorm** [comment]
Hi Sam,

Apologies for late reply. That's a plugin we were already using for the hub owners on the site so it's been tested and OK for you to use.

Cheers,

Tom

**Comment by samuk** [comment]
Great, thanks
