### ISSUE TITLE
Add analytics tracking to .PDF please

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#116]
It would be great to track downloads of .PDF's in Google Analytics.

Could you investigate and implement please.

http://www.blastam.com/blog/how-to-track-downloads-in-google-analytics

Thanks

Sam

**Comment by thisisyoke** [comment]
@arhinostorm should just be adding event tracking to the link right?

**Comment by thisisyoke** [comment]
Two things here. One is adding event tracking code to download links of pdf's. That should take 1 hour

The second would be to try to track the pdf like a url, so you would see number of views of your pdfs on your server. This is straight through GA and will take about 2 hours to setup.

Let me know if your happy to proceed

**Comment by arhinostorm** [comment]
Have added tracking to PDF download buttons... that is when you use the download custom field an d it creates a download button either at the top of a blog post or using a the flexible content area. This won't track links to pdfs that are just put in the copy.
