### ISSUE TITLE
Advice with Migration?

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#117]
Hi Jay, Tom

As you know i've been trying to get the old Drupal site moved from its current location in a /transitionnetwork.org vserver to a /oldtn.org vserver.

This will allow us to delete the current /transitionnetwork.org and recreate it with an up to date version of PHP as a home for the new Wordpress site.

There have been various trials and tribulations in trying to get this up and running. It's taking far too long and holding up your work on the other tickets. I realise it's outside of your remit really, but could I email you over the SSH passwords etc so you can see if you can quickly identify the problem with it?

Thanks

Sam

**Comment by samuk** [comment]
Put notes of what I've done[ here](https://docs.google.com/document/d/1t_WL9QrrGFIr4s46IE45pgd_sST-ENKq4Od1TRi9t3c/edit)

**Comment by samuk** [comment]
I suspect the issue is a https redirect, but I've commented all the rewrite stuff in .htaccess so not sure how that's happening.

**Comment by samuk** [comment]
OK got the .htaccess working. Some missing files, but I think this is basically resolved now. Just copying files.

**Comment by thisisyoke** [comment]
Ok sam, keep us posted. Tom is not actually booked ot be working on your site today so unfortunately he can not help just this second.

**Comment by samuk** [comment]
I'm still struggling with this i'm afraid. It would be good if you can offer any suggestions.

http://oldtn.org.dedi2835.your-server.de/training

I'm getting "Call to undefined function _tt_nav()" Which suggests a missing theme file? But everything appears to be in place.

When do you next have work scheduled for us? It might be helpful if Tom could have a look? 

Thanks

Sam

**Comment by thisisyoke** [comment]
Hi sam,

tbh this is outside of Tom's skillset. This is Drupal deugging/dev work and Tom does not touch that. We do have other drupal developers we could speak to, but they are not cheap. Do you want me to introduce you to them and you can negotiate some help with them? If we are involved it may be too expensive. Sorry if it sounds negative

**Comment by samuk** [comment]
Hi Jay 
Thank's no problem. There's a developer who's fairly familar with it, so I'll ask him in first instance..
