### ISSUE TITLE
Enable captions on photos

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#119]
"Captions for photos aren't showing, in spite of being typed into the Caption box"

Thanks

Sam

**Comment by thisisyoke** [comment]
show below the photo in small print, 12px . left aligned please

**Comment by arhinostorm** [comment]
The caption does work but you have to manually type it in when you insert an image in the rich text editor. If you add a caption in the media library to an image it won't automatically display when you insert that image into a rich text box. You have to click on the image, edit it and add a caption.
