### ISSUE TITLE
Page load time on map

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#122]
It would be great if we can get the map load time <4 seconds.

It's currently running around 12 seconds which is too long for users to wait really.

https://tools.pingdom.com/#!/ciPAJo/http://transitionnetwork.org/transition-near-me/

**Comment by thisisyoke** [comment]
will look into it. There is a lot of data to load but we will see if there is a way around one large initial wait

**Comment by arhinostorm** [comment]
Have completely rewritten this (was previously using a plugin for json output) and it is considerably faster. < 4 seconds.
