### ISSUE TITLE
Theme for download

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#123]
Hi we've had a couple of requests for hubs to use our theme.

Are you able to provide it as a .zip? Do you anticipate any issues with using it on other sites?

I could probably grab it via FTP and zip it up? But just thought it worth checking in with you too.

Thanks

Sam

**Comment by thisisyoke** [comment]
It doesn't have any 'front-end' menus to allow them to configure the site look and behaviour, like a crafted theme may have. As long as they have Wordpress knowledge they should be able to install it and set it up, but it wont be as straighforward as using a 'theme' that is set up to be easy

**Comment by samuk** [comment]
Thanks
