### ISSUE TITLE
Admins forced logout

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#124]
I've noticed that I sometimes get logged out of the site, Mike has also reported this and Naresh was logged out today. 

It's possible to log back in but it is slightly inconvenient. Any ideas on why this may be happening?

Thanks

Sam

**Comment by thisisyoke** [comment]
yeah, I noticed that too today. @arhinostorm any ideas? Seemed to happen only once after about 10 minutes of us starting

**Comment by arhinostorm** [comment]
I've just tried logging in and it's blocked me - seems to be caused by some added security plugin (wordfence?). I strongly suspect that that'll be the cause of the logout as it wasn't happening before. Have you installed many other plugins? 9 times out 10 is a plugin that causes the problem.

**Comment by samuk** [comment]
Hi Tom. No additional plugins have been installed. Wordfence does seem like a likely candidate. On the other hand it is blocking lots of robots/ brute force stuff.

What username were you trying to sign in under? I can see a failed attempt for 'administrator' in the logs. Was that you? 

Thanks

Sam

**Comment by arhinostorm** [comment]
That's not me - I use the transitiondemo user for all my logins.

**Comment by samuk** [comment]
Ah ok must have been a bot I guess.

Are you back in again now?

Thanks

Sam

**Comment by samuk** [comment]
This seems to have resolved itself.
