### ISSUE TITLE
Images added inside of posts using flexible content - getting cropped

### ISSUE THREAD

**Issue by thisisyoke** [transitionnetwork/TNv3.0#127]
If you add an image inside of a post using the flexible content image block it drops it. Can this be free to have tall images in there? as tall as the image you add?

**Comment by arhinostorm** [comment]
When you select an image you can pick the size - thumbnail, medium or large. Does large suit your needs?

**Comment by thisisyoke** [comment]
Rob was saying he was trying to add in a tall image and it was always getting cropped to the same, fairly square ratio, which you can see, all images added in the posts are the same size

**Comment by arhinostorm** [comment]
Have added a new image size that should sort this out
