### ISSUE TITLE
Unable to login using username - email OK

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#128]
Mike has created a user 'Sustainable Crediton'

https://transitionnetwork.org/wp-admin/user-edit.php?user_id=26438&wp_http_referer=%2Fwp-admin%2Fusers.php%3Fs%3Dinfo%2540sustainablecrediton.org%26paged%3D1

He's unable to log in using the username 'Sustainable Credition' although he is able to log in using the email associated with the account.

He's concerned that other users may also be unable to log in using their username in this case.
We investigated whether it was the space causing the issue, but he is able to log in using his account 'Mike Thomas' also with a space.

Have you got any idea why this could be happening? Could you update Mike on this ticket too please? michaelthomas@transitionnetwork.org

Thanks

Sam

**Comment by arhinostorm** [comment]
The username listed for this user is 'Mike Thomas'. I just created a user with username 'tombo' and password 'password' and can login with those details.

**Comment by thisisyoke** [comment]
To roundup - This username does not exist of 'Sustainable Crediton' it is listed as 'Mike Thomas'. We fear there was an input error here as the login system works fine. Can you try again creating a user and making sure there are no autosignups working on your browser perhaps. @samuk @ainsliebeattie
