### ISSUE TITLE
Spam users with no role

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#129]
I just spotted these two users

http://transitionnetwork.org/wp-admin/users.php?role=none

I can just delete them, but I wondered if you wanted to do some investigation into how they managed to create themselves without a role?

Thanks

Sam

**Comment by thisisyoke** [comment]
@arhinostorm be good for you to cast you eye over this and give your thoughts please

**Comment by arhinostorm** [comment]
Not sure where they have come from, but looks like spam based on names and email addresses. We've got around 26,000 people signed up and only two so far so it's safe to just delete them.
