### ISSUE TITLE
Ainslie not seeing excerpt section on Culture page in CMS

### ISSUE THREAD

**Issue by yvonnestruthers** [transitionnetwork/TNv3.0#13]
Ainslie is not seeing the excerpt content section in the CMS when she is editing this page see screen shot of what she gets below

http://transitionmovement.org/wp-admin/post.php?post=135&action=edit

<img width="1089" alt="screen shot 2016-10-05 at 3 30 44 pm" src="https://cloud.githubusercontent.com/assets/10939874/19117671/b36b499a-8b11-11e6-80df-386c79dcaa4f.png">

I see it fine when I go to the same page in the CMS and can edit - why is this / please can you recommend where ainslie can see it.

Checked permissions levels and we are both admin

**Comment by arhinostorm** [comment]
I can see the excerpt. You could try clicking the screen options button top right and making sure the excerpt checkbox is ticked.

<img width="1280" alt="screen shot 2016-10-06 at 11 26 11" src="https://cloud.githubusercontent.com/assets/1786472/19149030/be566c76-8bb7-11e6-8431-a68f4008bdf9.png">
