### ISSUE TITLE
Transition Map not working 

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#132]
Transition map doesn't seem to be working, it seems to be stuck in a loop.

Also it doesn't recognise postcodes properly, if you put in the first part it wil pick it up, i.e. bs16 but if you put in bs163ap then  it does not work.

**Comment by thisisyoke** [comment]
Hi Ainslie, 

the map is working fine for us, I will get a wider team to test. Try refreshing the page as Tom made a lot of optimisation to the way it works the other day

For the postcodes, that is beyond our control unfortunately. We are not using google for geocoding, so the results are not as good as if you were to use google maps outside the site.
