### ISSUE TITLE
Username vs email

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#133]
Hi - this from Mike:  I have noticed that usernames don't always work that well for people logging in, I wonder if we can change username to email on the login box, as you can login using your email. 

This will be useful for when I update the database I am going to make user profiles for the groups that have a info@tranistinsoandso.org email so if people leave their group they can still login using the generic email. So we then don't have to update stuff for people and mess around with changing users etc. 

Is this change possible and sensible?
Many thanks

**Comment by thisisyoke** [comment]
At present you can login with both email or username. I would suggest we just change the wording on the login panel to say "Username or email" and give people the option. If your happy I will mark this ready for Tom
