### ISSUE TITLE
Make main nav sticky as you scroll down

### ISSUE THREAD

**Issue by thisisyoke** [transitionnetwork/TNv3.0#135]
Headroom js is the best solution here. As you scroll down the mani nav can stick to the top and have a different state, a more compressed state. As you scroll back up it will then regain it's normal positioning.

Estimate, Design time: 1 hour

@arhinostorm please estimate dev time

**Comment by arhinostorm** [comment]
3 hours - menu has a lot of items in it, gonna be a fairly chunky fixed nav?

**Comment by ainsliebeattie** [comment]
is there any way to not have the whole menu - just the top buttons - we don't want clunky!

**Comment by thisisyoke** [comment]
Tom was saying 'chunky' as in heavy..it would have the rollover panels as well. We could perhaps create an alternate version of the main buttons @arhinostorm which don't have the html for the rollover panels in there so it is lighter?

**Comment by samuk** [comment]
When testing this on /dev I have some issues moving to the menu items.

On Chrome 55 whatismybrowser.com/w/5B4EW2D

1) Hover over top menu item (eg stories) This causes menu to pop open. 

2) Then move cursor downwards towards menu item 'view all stories'

3) The menu disappears.

Could you test and see if you are able to replicate this?

Thanks

Sam
