### ISSUE TITLE
word count on contact page

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#138]
Report from admin today - third person today who has tried to reach us via the contact us page and wasn’t able to due to system telling them they are over the word limit when they clearly aren’t.

Can you please URGENTLY look into why people cannot ask us longer questions.

Cheers

**Comment by thisisyoke** [comment]
When you say 'clearly aren't' do you mean they have not entered in 600 characters? There is a limit of 600 characters on the main box. We can just remove that if you wish.

But if you are saying people are getting a limit reached message when they are adding less than the 600 allowed characters, then that is a separate issue.

**Comment by thisisyoke** [comment]
@ainsliebeattie

**Comment by ainsliebeattie** [comment]
Hi @thisisyoke - sorry it has been a bit frantic here.  I believe it is the limit issue but Sam is investigating now and will come back to you today.

**Comment by arhinostorm** [comment]
I have removed the limit for now.

**Comment by samuk** [comment]
Thanks Tom.
