### ISSUE TITLE
Single password for UAT testing users

### ISSUE THREAD

**Issue by yvonnestruthers** [transitionnetwork/TNv3.0#14]
A single sign in in order to view the site is needed for UAT testers. 

Turn off current plugin hiding the site and implement standard way of hiding the site. 

Needs to be implemented before Wednesday 12th

**Comment by yvonnestruthers** [comment]
Hey @arhinostorm  could you implement this one as well please? Thanks!

**Comment by arhinostorm** [comment]
This is done.

un: yoke
pw: transitioning2016!
