### ISSUE TITLE
Cannot edit site properly!

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#140]
Hi - Rob and I have both lost the edit rights to the home page in terms of changing the front of the site.  We don't have the black bar up the top when we are logged into the site through wp-admin and therefore we cannot promote our blogs, change the front slider scale or anything else that we need to do. This is stopping us progressing with our day to day work and is vital that it is fixed immediately.  Can you please look into it.
thanks

**Comment by thisisyoke** [comment]
I need to change your password and try logging in as you. I will log you out.. just in case you wonder what is happeneing

**Comment by ainsliebeattie** [comment]
thanks that's fine

**Comment by thisisyoke** [comment]
Hmm, I can login fine as you and edit the page. So I login here:

https://transitionnetwork.org/wp-login.php

Used your email address and a new password: tn23!21ain

All I can think is that the Wordfence plugin is logging you out. I will disable it now for a day to test it out

**Comment by ainsliebeattie** [comment]
yes you are right - must be wordfence.  So - does rob need a new password
or will it just work given the disabling of wordfence?


Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb

**Comment by thisisyoke** [comment]
no, he shouldn't. Might just need to signin twice which seems to be the case at the moment. I am hesitant to diable wordfence without doing it thoroughly on the staging environment first. If you can both login by doing it twice then we will look at wordfence using the maintenance time

**Comment by ainsliebeattie** [comment]
what do you mean by doing it twice - it only asked me one and worked...


Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb

**Comment by ainsliebeattie** [comment]
...and now it wont let me in on the second log in....aaaagggghhh


Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb

**Comment by ainsliebeattie** [comment]
no no ignore me - just froze.

Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb

**Comment by ainsliebeattie** [comment]
So - what actually is wordfence for and given that it is sending me all
sorts of strange things and stopping people doing stuff - what would you
recommend instead?
cheers

Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb

**Comment by ainsliebeattie** [comment]
Can you please give Rob a new password as he still can't get in.

**Comment by thisisyoke** [comment]
Wordfence is used to generally protect the site from hacking and unwanted traffic. It does seem beneficial, it just needs some attention. As I mentioned, we have not used it before, so once tom gets to grips with it I am sure it will be fine. 

Rob can just click the forgotten password link on the login page if he needs to change his password.

https://transitionnetwork.org/wp-login.php

**Comment by thisisyoke** [comment]
But shout if you need me to do it manually for him
