### ISSUE TITLE
Promoblocks not working

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#141]
Hi - only one promoblock is working. I have just added a new one that is critical and nothing appears - you can see in the edit that I put information in - including an image - and nothing is showing. Can you please help me. This is quite urgent and I have to do another one today that is critical and if this isn't working it will be a big issue for me.  I would really appreciate your urgent attention - what am I doing wrong?
https://transitionnetwork.org/news-and-blog/promoblock/municipalities-project-recruitment/?preview_id=10821&preview_nonce=582e1579a4&preview=true

**Comment by thisisyoke** [comment]
Hi ainslie. So I can see you have created your promoblock ok. Have you tried adding it to the page you want it to show on? Once you have published your promoblock, you then have to go to the page you want it to display on and choose it from the list of promoblocks. This works fine for me in testing.

**Comment by thisisyoke** [comment]
This is the promoblock option in the page editing screens: 
![image](https://cloud.githubusercontent.com/assets/4559257/24365591/691d7a22-130e-11e7-8244-671518f59797.png)
choose one from the list on the left and it will move to the right. Save changes and it will show

**Comment by thisisyoke** [comment]
@ainsliebeattie are you happy with this now? In the future if you are please close any issue you feel has been resolved. thanks

**Comment by ainsliebeattie** [comment]
I am happy with it and I do close them when I get the chance to come back - as per the one I closed 2 days ago! Just a bit on the busy side. Sorry.
