### ISSUE TITLE
uploading documents not working

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#15]
When I upload a document to the media library it comes back and says the image is too small. I have a load of documents that need uploading.  I am selecting the file as I should be but the media library seems to be expecting an image.

<img width="1120" alt="screen shot 2016-10-06 at 1 15 01 pm" src="https://cloud.githubusercontent.com/assets/22507393/19151863/0ff1f9f6-8bc7-11e6-974c-236f15cc5071.png">

note the bottom line if this pic has uploaded - will also email it to ella just in case...

**Comment by arhinostorm** [comment]
There was a check to stop you uploading images that were too small... a failsafe so you didn't add hero images that were tiny, things like that. Have turned it off for now, so you should be able to upload any size image... just be careful when adding images to news items etc that they are large enough to look decent as a hero.

**Comment by ainsliebeattie** [comment]
thanks but I am not adding an image - I am adding a document - is this not the right place to be adding a document then?

**Comment by arhinostorm** [comment]
The image check was just a bit over zealous. This should fix the document issue as well.

**Comment by ainsliebeattie** [comment]
all done and working - thankyou!
