### ISSUE TITLE
Process for Geocoding when editing initatives

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#16]
This morning we spotted a load of initiatives off the coast of Africa that need to be geocoded (they were never geocoded in Drupal for some reason and have a lat/long of 0.000000/ 0.000000)

I've logged into Fujino for example http://transitionmovement.org/wp-admin/post.php?post=2794&action=edit

I can use the search at the bottom of the page to find Fujiino on the map, but there's no obvious way of copying the lat/long into the Initiative record. Am I missing something? Or do we need to work out a method to do this?

**Comment by arhinostorm** [comment]
If you use the map at the bottom of the page and scroll back up and click 'update' (i.e save the page) it copies across the lat and lng for you.
