### ISSUE TITLE
ease of finding related content

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#17]
Hi - I am trying to put related content into the site - the purpose page to be precise.  I am trying to find this blog https://transitionnetwork.org/blogs/rob-hopkins/2015-11/transition-story-time-stop-talking-about-climate-change  but when I search it is not coming up - is there a simple way that isn't going to see me scroll for ages even when I have the title correct?

<img width="861" alt="screen shot 2016-10-06 at 2 16 24 pm" src="https://cloud.githubusercontent.com/assets/22507393/19153701/80f45a42-8bcf-11e6-8663-0c1d383df9dc.png">

**Comment by thisisyoke** [comment]
Hi Ainslie, looks like you have a mis-spelling in your title. I just did the same and searched for:

The Transition Story: Time to stop talking about climate change

I copied the title of the post.

And it gave me 5 results, the one I was looking for being one of them

**Comment by ainsliebeattie** [comment]
doh - sorry!!
