### ISSUE TITLE
people page is missing

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#19]
going a little nuts here.  the people page is missing. if you remember when we were learning with Jay we had a people page with the titles important, less important ect. It was sitting within the about the movement section as it was where our board and staff were to be listed. This page is now missing! asm I supposed to rebuild it or have you just hidden it?

**Comment by yvonnestruthers** [comment]
Someone has deleted the page (no one here) I've just set up a new people page for you.

**Comment by ainsliebeattie** [comment]
thankyou!

Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb
