### ISSUE TITLE
embed video not working

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#20]
i am trying to embed a couple of videos in the international hubs circle page and they wont appear on the screen - just the embed text.  when I try and click on the embed button nothing happens. What am I doing wrong?

**Comment by yvonnestruthers** [comment]
I just did a test on this page and I can see the video both in the back end and when I publish - I just copied the url of the video I wanted to embed and pasted it directly into the text box 

http://transitionmovement.org/embed-test-page/

**Comment by ainsliebeattie** [comment]
[image: Inline images 3]

here is evidence - I have copied embed code and cut it into text in the
same way you have suggested you have done...

[image: Inline images 2]

Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb

**Comment by yvonnestruthers** [comment]
You dont need to copy the embed code, only the actual URL and it will embed automatically. 

So in my example I just pasted https://www.youtube.com/watch?v=VXo_Jwsa3CM and it embeds the video
