### ISSUE TITLE
need a text box on people pages template

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#22]
Hi - I need the ability to add text boxes on the people template so that I can explain that section of people that we are showing. An example is that I am trying to include trainers in different countries - so I need to say the country name and a few sentences about the training in that country. It will be the same with the meet the transitioners page - the ability to add text at the beginning to give a few sentences blurb will explain things more clearly.

**Comment by yvonnestruthers** [comment]
Hi @ainsliebeattie this one will need to be a change request as we're adding something different from the designs. It's fairly simple to implement - we'd need 0.5 hours design time, and 0.5 hours development time. total - 1 hour - £39.30. Let me know if that's OK.

**Comment by ainsliebeattie** [comment]
yes please - please go ahead with it.
cheers

**Comment by yvonnestruthers** [comment]
Thanks Ainslie. I've booked in for Jay to do the design work first thing tomorrow morning. 

I'll put the CR paper work in the shared folder for you as well.

**Comment by thisisyoke** [comment]
Hi @ainsliebeattie , how would this be for you:

![image](https://cloud.githubusercontent.com/assets/4559257/19263832/2ed2db1a-8f96-11e6-8a7d-0f719dc02d0a.png)

If your happy please say so and we will implement it

**Comment by ainsliebeattie** [comment]
hi - yes this is great - can I implement this wherever I am adding people
or is it only at the top of this page?

cheers

Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb

**Comment by yvonnestruthers** [comment]
Hi Ainslie, you would be able to use the text box under each group title. So you could have: 
- First group title
  -text box blurb
- photos
- second group title
- text box blurb
- photos

But the text box must come under the group title. So you couldn't have:
- first group title
- photos
  -text block blurb
  -photos

I hope that makes sense. Does that sound OK?

**Comment by yvonnestruthers** [comment]
approved please implement @arhinostorm
