### ISSUE TITLE
Train the trainer page  = block text doesn't look right

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#24]
Can you take a look at this page and see what we can do about this text - it looks terrible?
<img width="1047" alt="screen shot 2016-10-10 at 10 00 09 am" src="https://cloud.githubusercontent.com/assets/22507393/19231178/7e08ad98-8ed0-11e6-9044-21a061e58063.png">

**Comment by yvonnestruthers** [comment]
http://transitionmovement.org/wp-admin/post.php?post=7215&action=edit

@arhinostorm I can see formatting in the CMS that isn't pulling through into the front end. I think it may be a similar issue to the previous one re flexible content blocks formatting. Please can you take a look. Thanks!

**Comment by ainsliebeattie** [comment]
also happening on transition Thrive
