### ISSUE TITLE
Permissions to add hubs

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#26]
Hi Ella

I had a go at adding a hub, but I couldn't see a submit/publish button.

Do I need additional permissions to be able to add hubs?

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

This looks like a javascript error - I'll assign to Tom to address

**Comment by yvonnestruthers** [comment]
@arhinostorm please can you take a look at this one

**Comment by arhinostorm** [comment]
This is an error with the custom fields. The hubs old data fields that are of type user are causing the problem.

@thisisyoke do we need all these fields (each of them is type user)?  
Profile also editable by
web point of contact
Primary point of contact
People and contacts

**Comment by thisisyoke** [comment]
No, lets delete them.
