### ISSUE TITLE
Making trainings children of training types

### ISSUE THREAD

**Issue by yvonnestruthers** [transitionnetwork/TNv3.0#28]
I've now spotted that we should have been creating 'training types' then creating trainings as children of this. I'm still not quite clear how we set the 'trainings' to be children of the 'training type' for example;

In my test one: http://transitionmovement.org/wp-admin/post.php?post=7274&action=edit I have selected 'Thrive' check box on the right.

And it appears here:
http://transitionmovement.org/wp-admin/edit.php?post_type=trainings&trainingtype=thrive

But it's not yet appearing on this page: http://transitionmovement.org/do-transition/training/trainings/

Is there a step I'm missing here?

**Comment by yvonnestruthers** [comment]
Hi Sam,

Just commenting here on the making trainings children of training types - the process you have described is correct (ticking the box on the right)

I have done a test this morning and it's not pulling through to the front end page for me either so I'm going to ask Tom to look into this one for us. Carry on as normal, ticking the relevant boxes to make the trainings children and they will appear in the front end once this issue is fixed. 

Hi @arhinostorm please could you have a look into the above?

**Comment by samuk** [comment]
Thanks for looking at this one. I'm still not seeing this Training http://transitionmovement.org/wp-admin/post.php?post=7308&action=edit

Appearing under the 'Effective groups' title here: http://transitionmovement.org/do-transition/training/trainings/

I'm also not yet seeing the 'Launch' or 'launch online' training types appearing here:  http://transitionmovement.org/do-transition/training/trainings/

Ref
http://transitionmovement.org/wp-admin/edit-tags.php?taxonomy=trainingtype&post_type=trainings

Thanks

Sam

**Comment by arhinostorm** [comment]
there was one more issue with it, if there is only 1 item in each group. Now fixed.
