### ISSUE TITLE
Layout on trainings pages - intro text column width

### ISSUE THREAD

**Issue by yvonnestruthers** [transitionnetwork/TNv3.0#29]
re the layout of trainings pages - it looks correct comapred to the design, apart from that the intro text should not be the same column width as the body text beneath, it should continue over the date and time info. I think when the details which go in the RHS are in it will look more comfortable.

**Comment by yvonnestruthers** [comment]
@arhinostorm example of the intro text wrapping too quickly is here: 
http://transitionmovement.org/do-transition/training/trainings/thrive-training/ 

Design here: 
https://projects.invisionapp.com/share/3V7LEZPDW#/screens/174227586

Can you address the intro text wrapping at the same time as the body,when it should continue over the date and time bit.

**Comment by arhinostorm** [comment]
The only way to fix this is to have the first paragraph entered in a separate text box (which we'd have to create) in the CMS.

**Comment by yvonnestruthers** [comment]
Ok - I think we need to do that so that it matches the design please.

**Comment by arhinostorm** [comment]
Have added a custom field of 'intro_paragraph'. The first paragraph should go in this field and be removed from the main editor.

**Comment by samuk** [comment]
The text wrapping is still not working for me on the training pages. Eg

http://transitionmovement.org/do-transition/training/trainings/effective-groups/

The Date/time and location float over to the left. The first paragraph is also appearing in bold/ header type text. Is this intentional?

Thanks

Sam
![contact](https://cloud.githubusercontent.com/assets/400875/19517804/4f8a1484-95fb-11e6-9105-fb892d7b9225.png)

**Comment by yvonnestruthers** [comment]
Hi Sam,

Both these things are intentional and are part of the approved design - please see the link I pasted above (https://projects.invisionapp.com/share/3V7LEZPDW#/screens/174227586). 

Tom added the additional text box for the intro to get that wrapping differently - as per the design that needs to wrap to a wider text column and also be the larger sizer. 

If you're really adverse to this in certain instances, you can not use the intro text area, and go straight into the body text area, which would look like the below screenshot, however enlarging the intro text was a part of the design and is something that we're doing throughout the site so I probably wouldn't reccommend that approach as a rule

![screen shot 2016-10-19 at 13 39 36](https://cloud.githubusercontent.com/assets/10939874/19518996/c516d39e-9601-11e6-9f09-124fe91ad39e.png)
