### ISSUE TITLE
promo block formatting wrongly for Ainslie

### ISSUE THREAD

**Issue by yvonnestruthers** [transitionnetwork/TNv3.0#30]
Issue is on this page: http://transitionmovement.org/do-transition/inner-transition/

And the below is happening - I can't replicate and am on the same browser (latest version of Chrome) why would this be happening? @arhinostorm can you comment? 

<img width="924" alt="screen shot 2016-10-12 at 1 49 20 pm" src="https://cloud.githubusercontent.com/assets/10939874/19312522/a730b8e4-908a-11e6-9382-395bdad69cef.png">

**Comment by arhinostorm** [comment]
This is a combination of how big you've got your browser window open and there being a lot of text in the promo block. I've made the block slightly taller to accommodate this.
