### ISSUE TITLE
Site emails come from "jay@thisisyoke.com" <transitionwebmail@gmail.com>

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#31]
Hi all 

I did a test email from the (still unfinished)  http://transitionmovement.org/contact/

It came through from "jay@thisisyoke.com" transitionwebmail@gmail.com

I think they are supposed to come from websupport@transitionnetwork.org?

Is this still on your to-do's?

Thanks

Sam

**Comment by yvonnestruthers** [comment]
@arhinostorm can you check this please

I just checked in the email settings http://transitionmovement.org/wp-admin/options-general.php?page=wp-mail-smtp%2Fwp_mail_smtp.php

and emails are set to come from websupport@transitionnetwork.org (which is correct)

so this one must be coming from another setting. Could you let me know where to change?

**Comment by arhinostorm** [comment]
I think this is set in the options page:

http://transitionmovement.org/wp-admin/admin.php?page=acf-options

It's called initiatives email, but it's for contact as well.

**Comment by yvonnestruthers** [comment]
I've just changed it in the options page to websupport@
