### ISSUE TITLE
Links to hub websites prefixed with Transitionmovement.org URL

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#36]
The links from Hubs pages to the hub websites

Eg http://transitionmovement.org/transition-near-me/hubs/argentina/

End up prefixed with transitionmovement.org.

So www.entransicion.com.ar/

Becomes

http://transitionmovement.org/transition-near-me/hubs/argentina/www.entransicion.com.ar/

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Not sure on this one @thisisyoke @arhinostorm please can you advise? Thanks!

**Comment by thisisyoke** [comment]
@yvonnestruthers this is a bug, the link is not working correctly. If Tom could fix it that would be great. It needs to lose the prepend page url

**Comment by thisisyoke** [comment]
@arhinostorm can you please fix this broken link as part of todays work

**Comment by arhinostorm** [comment]
Links need the http:// prefix in wordpress, otherwise it thinks it's an internal link and adds the root url on to it.

**Comment by thisisyoke** [comment]
Ahh ok, there you go @samuk please prefix with http://

**Comment by samuk** [comment]
Hi all

I'll make sure I do this with any new content created. It's mainly affecting the Initiatives that you've migrated over:

eg
http://transitionmovement.org/transition-near-me/initiatives/abergavenny/
http://transitionmovement.org/transition-near-me/initiatives/abingdon-carbon-cutters/

Can you look into fixing it for the migrated content please.

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Thanks Sam. 

@arhinostorm is there a way of automatically prefixing the links in initiatives with http:// ?

**Comment by yvonnestruthers** [comment]
As discussed on slack, please implement a check on hubs and initiative pages and if http is missing, add it automatically
