### ISSUE TITLE
Map still Eurocentric

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#38]
We discussed with Jay making the map load on a world view rather than a Eurocentric view.

http://transitionmovement.org/transition-near-me/

Thanks

Sam

**Comment by thisisyoke** [comment]
yep, sorry. here is the mockup:

![image](https://cloud.githubusercontent.com/assets/4559257/19566636/f369f74e-96e2-11e6-932f-ef7e2804b2d7.png)

**Comment by yvonnestruthers** [comment]
@samuk are you happy with the mock up above? If so I will ask Tom to implement. Thanks, Ella

**Comment by samuk** [comment]
Yes please.

**Comment by yvonnestruthers** [comment]
Hey @arhinostorm please could you change the map to appear as per the mock up above? Thanks!
