### ISSUE TITLE
Text not appearing on hub entries

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#39]
I've added text
http://transitionmovement.org/wp-admin/post.php?post=7803&action=edit

But it doesn't appear on the frontend
http://transitionmovement.org/transition-near-me/hubs/reseau-transition-be/

Ref http://5ufovq.axshare.com/#g=1&p=hub_single&c=1

Thanks

Sam

**Comment by yvonnestruthers** [comment]
@arhinostorm please can you address?
