### ISSUE TITLE
Stories page

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#42]
top line comment and boxes not fitting in properly
<img width="1053" alt="screen shot 2016-10-21 at 11 31 54 am" src="https://cloud.githubusercontent.com/assets/22507393/19636751/3a9dc31a-99c3-11e6-9ef4-e82a20d4ffaa.png">

**Comment by thisisyoke** [comment]
Looks like we completed this by moving the dropdowns to the section below. I will close now
