### ISSUE TITLE
bulleted lists spaced too far apart

### ISSUE THREAD

**Issue by MikeTransition** [transitionnetwork/TNv3.0#5]
The bullet points are spaced very far apart, see this page

http://transitionmovement.org/do-transition/starting-transition/7-essential-ingredients/vision/

**Comment by yvonnestruthers** [comment]
The spacing is added so that when you have bullets with more than one line of text like the example below there is enough differentiation 

![pasted image at 2016_09_23 11_58 am](https://cloud.githubusercontent.com/assets/10939874/18785497/71362e30-8190-11e6-9de9-9750fa968b47.png)
