### ISSUE TITLE
can't edit training page

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#50]
We can't seem to edit this page....
<img width="1149" alt="screen shot 2016-10-24 at 8 41 27 am" src="https://cloud.githubusercontent.com/assets/22507393/19637217/c00b2f90-99c5-11e6-806c-f1031934119e.png">
Ideally (and this might answer last issue raised) we would have How training woks in this movement > then info about program and courses > then calendar to find out what trainings are available now in what country - and maybe a visual listing of those courses

**Comment by yvonnestruthers** [comment]
You can't add content onto here, as it's a listings page for custom post types (in this case trainings). As I've said on the last issue, it seems like there needs to be some thinking around how your users will be looking for courses and we can create a scope to develop this area based on that. But it's not something that's included in the scope for phase 1 so would need to be either a CR or go into phase 2. At this stage, I'd recommend this going into phase 2 as it would be worth having some time to think through the right approach before implementing anything. 

I have started a list of things to discuss as potential items for phase 2 - I'll share it with you so you can be adding things as well.

**Comment by ainsliebeattie** [comment]
I am going to close this issue as it is something we can pick up later if we need to.
