### ISSUE TITLE
sticky buttons?

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#52]
We discussed and requested sticky buttons on several occassions and listed them in our requirements doc.  They are currently not sticky. When will they be?

**Comment by yvonnestruthers** [comment]
This isn't something that is included in the requirements for this project as part of the PID, so would need to be estimated seperately as part of the work for phase 2. This will certainly need some further scoping to understand which items you require to be sticky. If you could list those out I will add them into our list of items to be considered for phase 2 of development. Many thanks

**Comment by yvonnestruthers** [comment]
As discussed @ainsliebeattie if you can add a brief of the requirements for this in here, we can look at the time that will be required, and make a decision as to whether this can realistically be completed before go live or not. Thanks!

**Comment by yvonnestruthers** [comment]
Decision made to hold off on this one until post launch. Ainslie and Sarah to discuss and put together a brief for this and then to be discussed with Jay.

**Comment by thisisyoke** [comment]
@ainsliebeattie do you have the brief yet? We could action this work as part of Jan or Feb's maintenance budget I would imagine. once you send over the details I will get a cost together for you

**Comment by ainsliebeattie** [comment]
will have something with you for early feb.
