### ISSUE TITLE
Category filter not respected on stories

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#55]
If I filter for 'Reconomy' On the stories page

http://transitionmovement.org/stories/?topic=reconomy&country=

All content is presented and the filter not respected.

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam - thanks for logging. 

@arhinostorm I'm getting this issue with all the filters on the stories page. I'm also finding that when you filter by country and topic, it just shows all the content in that country - eg the belgium example below I filtered by 'Built environment' and 'Belgium' - but the content it's showing me is food and drink http://transitionmovement.org/stories/?topic=built-environment&country=be
![screen shot 2016-10-27 at 12 30 34](https://cloud.githubusercontent.com/assets/10939874/19765669/7cf6af30-9c41-11e6-9c8d-e2965e126756.png)

Please can you take a look as part of the UAT fixes time next week? Thanks!
