### ISSUE TITLE
Quotes overun on /home

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#57]
![quotescutoff](https://cloud.githubusercontent.com/assets/400875/19772871/7b04c9c8-9c5f-11e6-91b4-36a6a73d75de.png)
On the homepage the quotes do not appear correctly at the bottom of the page.

I realise they are quite long, but 2/3 appears to contain two separate quotes?

**Comment by yvonnestruthers** [comment]
Hi Sam,

This is simply a result of the length of the quotes being put in there - they are too long for the space. I just tested this by replacing the quotes 1 and 3 which are really long with the text of Quote 2. When I do that it's all working well. I'm afraid it's going to be a case of needing to edit/find briefer quotes for this section. See screen shots below (Don't worry I've now returned the content to how you'd inputted it) 

![screen shot 2016-10-27 at 16 12 43](https://cloud.githubusercontent.com/assets/10939874/19773232/b412c912-9c60-11e6-8303-479be9f66bec.png)
![screen shot 2016-10-27 at 16 12 52](https://cloud.githubusercontent.com/assets/10939874/19773243/bbf0ce90-9c60-11e6-891d-e006a983c85e.png)
![screen shot 2016-10-27 at 16 12 57](https://cloud.githubusercontent.com/assets/10939874/19773249/c04f8a30-9c60-11e6-9126-df5650c2a48d.png)
