### ISSUE TITLE
Implement Mailchimp for newsletter sign up 

### ISSUE THREAD

**Issue by yvonnestruthers** [transitionnetwork/TNv3.0#59]
Hi Sam

We need to finalise the Mailchimp set up on the site for the subscription to the newsletter. Please can you do the following: 

- Amend my log in to your Mailchimp accound to be admin level (this will allow us to go in and do the settings elements that need to happen at a list level). 
- Confirm the list which subscribers need to be added to within Mailchimp

Many thanks

**Comment by samuk** [comment]
Hi Ella

I've just made you an admin.

The list is ' Transition Network' it has around 27k subscribers.

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Perfect, thank you Sam. 

@arhinostorm I've screen shotted the list which recipients need to be added to below: 
![screen shot 2016-11-01 at 15 10 59](https://cloud.githubusercontent.com/assets/10939874/19894641/a3c4902a-a045-11e6-8f20-d5f22465ad6e.png)

Log in details I've given you off Github. 

Need to link this list up to the Mailchimp form in the footer, and also the subscription tick box in the user registration form.
