### ISSUE TITLE
Bullets not appearing in faq text

### ISSUE THREAD

**Issue by MikeTransition** [transitionnetwork/TNv3.0#6]
On this page

http://transitionmovement.org/do-transition/starting-transition/7-essential-ingredients/community-involvement 

If you go down to faq question How can we get our events promoted in local media? 
the points here should be bulleted, as they are in the faq box in the backend.

How to write a good press release
How to engage with local media – understanding their needs
How to create ‘media friendly’ events.
How to speak on radio or TV
How to tell the Transition story

**Comment by yvonnestruthers** [comment]
One for you @arhinostorm please

**Comment by yvonnestruthers** [comment]
Resolved - see screenshot below

![screen shot 2016-09-28 at 10 18 59](https://cloud.githubusercontent.com/assets/10939874/18907845/31687122-8565-11e6-9a74-b0034218a587.png)
