### ISSUE TITLE
Embedding Joomag

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#60]
Hi We're going to be using Joomag on the site

Could you enable a way for us to embed it please?

<iframe name="joomag-embed-b2d173be-739c-462d-9798-5993a4a6e7a5" style="width:900px;height:587px;" width="900" height="587" hspace="0" vspace="0" frameborder="0" src="//www.joomag.com/magazine/the-essential-guide-to-doing-transition-primer-english-september-2016/0311358001472826045?e=1&amp;page=1&amp;embedInfo=;image,//www.joomag.com/static/flash/gui/themes/backgrounds/wood.png,fill"></iframe>

I see there is a plugin available: https://wordpress.org/plugins/wp-joomag/ 

Or we could just allow iframes in functions.php ?

Thanks Sam

**Comment by yvonnestruthers** [comment]
This one would need to be a change request - please could you estimate how long this would take you to complete and test @arhinostorm 

Thanks!

**Comment by yvonnestruthers** [comment]
Hi Ainslie/Sam,

Is this something that can wait until after go live? Perhaps we could address it in December's maintenance? 

Thanks

Ella

**Comment by ainsliebeattie** [comment]
Hi Ella - really sorry but this must be done for launch - loads of work has gone into getting this ready in time.  cheers

**Comment by yvonnestruthers** [comment]
Hi Ainslie,

I will ask Tom to assess and estimate this as part of the estimate for the additional functionality which needs to be completed before go live, and to see if this is possible within the time that is available within our current timelines. I will confirm if Tom has sufficient time available before go live to complete everything as soon as I hear back. 

Many thanks

**Comment by yvonnestruthers** [comment]
@arhinostorm please find some example joomags here: https://www.joomag.com/en/newsstand/client-magazine-example-2014/0065784001416243646

**Comment by yvonnestruthers** [comment]
Hi @ainsliebeattie and @samuk 

I just had a chat with Jay and there was a crossed wire on this one - we don't actually need to do any extra work, as you can embed Joomags already by going the the source code in the wiziwig (looks like <>) and putting the Joomag code in there.

I'll close this issue now. 

Thanks

Ella
