### ISSUE TITLE
Adding text to translate popup

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#62]
Hi we'd like to add some text to the popup that appears when you click the translate button.

"We're working on <Transition in your language | link> 
The below translations are powered by Google.

Could you quote for this please.

Thanks

Sam

**Comment by yvonnestruthers** [comment]
![screen shot 2016-11-01 at 13 37 55](https://cloud.githubusercontent.com/assets/10939874/19891728/4d41de30-a039-11e6-94a5-d6e169913aa4.png)

Here's the languages box as it stands - @arhinostorm please could you quote to add the wording as per Sam's comment above? I will then estimate this as a Change Request. Thanks!

**Comment by arhinostorm** [comment]
Sorry, don't think is possible. The google translate plugin doesn't have an options for adding text and the widget loads an iframe in, so it's really hard to amend stuff as it's all injected via javascript. Any solution (if there is one) we found would be really hacky, and probably against the terms of service for the plugin as well.
