### ISSUE TITLE
404's since uploading .htaccess

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#63]
Hi I uploaded the .htaccess and since then we've been getting 404's across the site for everything apart from the homepage?

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

Can you try clearing your cache and then trying - it's working for me when I've done that. Let me know.

Thanks

Ella

**Comment by samuk** [comment]
Works this morning :)
