### ISSUE TITLE
weird bullets appearing on essential ingredients pages

### ISSUE THREAD

**Issue by MikeTransition** [transitionnetwork/TNv3.0#7]
On the essential ingredients pages, there seems to be random bullets circles appearing see these page scroll down to where the resources and they are on the right hand side. 
http://transitionmovement.org/do-transition/starting-transition/7-essential-ingredients/healthy-groups/

They seem to appear on all of the essential ingredients pages that are linked to from here:
http://transitionmovement.org/do-transition/starting-transition/7-essential-ingredients/

Cheers,
Mike

**Comment by MikeTransition** [comment]
It seems that the amount of bullets are related to the amount of resources embedded.

**Comment by yvonnestruthers** [comment]
Thanks for reporting Mike.

@arhinostorm please could you address when you're working through Jay's issues tomorrow?

**Comment by yvonnestruthers** [comment]
Dealt with on the internal TN repo
