### ISSUE TITLE
Password protection is disabled

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#71]
Hi I seem to be able to access the site without a password:
https://tools.pingdom.com/#!/b0rjI/transitionmovement.org

Could you re-enable?

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam - I'm checking this one with Tom and will ask him to re-enable if it has been turned off for any reason. 

@arhinostorm please can you confirm

Thanks

Ella

**Comment by arhinostorm** [comment]
someone has removed the password stuff from htaccess. It's back in now.
