### ISSUE TITLE
Donate button link edit in header

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#73]
The donate button seems to go to http://transitionmovement.org/donate/login

Could you re-point to http://transitionmovement.org/donate

(Or is there a way I can edit these buttons?)

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam

I believe that the header and footer are hard coded, as once set they do not change - that's fine to change the link though of course. 

@arhinostorm the donate button in the header needes to go here please: http://transitionmovement.org/donate

Thanks

Ella
