### ISSUE TITLE
Authors on the blog

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#75]
Hi - we have talked before about the need for different authors names to appear on the blog....I thought we would be able to highlight if an author that was not an editor wrote something, we would be able to highlight that it was not the person who posted that wrote..eventually resulting in the ability to sort between authors when searching. This is really important to us as we will be heading towards guest editors and guest writers more and more.  Is this  a simple addition, something that has been missed (because it has obviously been missed by me since our first discussions of it) and can it be remedied easily?   My example is this one here - clearly at the top I have added in that it is written by claire, but it comes up by rob on the main blog section.... http://transitionmovement.org/news-and-blog/spring-cleaning-our-transition-groups/?preview_id=5368&preview_nonce=b3b64942a2&_thumbnail_id=7797&preview=true

**Comment by yvonnestruthers** [comment]
Hi Ainslie,

If I'm understanding correctly there are 2 questions here: 

1) Whether someone who is not the original author of a post can be selected to show as the author
2) Whether someone who does not have editing permissions on the site can be selected as a post author

Answers to each of these are as follows: 

1) Yes, you can select someone else to appear as the author of a post as long as they have the permission level contributor or higher (see authorisation levels below):

Super Admin – somebody with access to the site network administration features and all other features. See the Create a Network article.
Administrator (slug: 'administrator') – somebody who has access to all the administration features within a single site.
Editor (slug: 'editor') – somebody who can publish and manage posts including the posts of other users.
Author (slug: 'author') – somebody who can publish and manage their own posts.
Contributor (slug: 'contributor') – somebody who can write and manage their own posts but cannot publish them.
Subscriber (slug: 'subscriber') – somebody who can only manage their profile.
- You can select another author that is different to the original author by going to the post in post list, and then clicking on 'Quick edit'. 
  ![screen shot 2016-11-16 at 09 38 10](https://cloud.githubusercontent.com/assets/10939874/20341982/7501295a-abe0-11e6-93f9-fbf8695b7bba.png)
- Then you'll see a list of authors to choose from 
  ![screen shot 2016-11-16 at 09 39 01](https://cloud.githubusercontent.com/assets/10939874/20341998/88a7fa56-abe0-11e6-94fa-ae95c730ca3a.png)
- As an example, I've changed the author of the Spring Cleaning article to be you, which now appears in the front end: 
  ![screen shot 2016-11-16 at 09 40 08](https://cloud.githubusercontent.com/assets/10939874/20342058/c864bfc6-abe0-11e6-9aa7-fd8f57b7c23e.png)

2) For people that you would like to contribute material to the site (eg the guest writers you mentioned), but not to be able to edit anything else, you should set them up as 'Contributors' - this means that they can create content (eg a new blog post) but not publish it, and they also cannot edit anyone elses content. In the event that you want to input the content on behalf of the person, but have them appear as the author, you will simply need to create a user profile for that person with 'Contributor' permissions and then select their name from the author list. 

I hope that helps.

Ella
