### ISSUE TITLE
people page - images not showing in Safari

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#77]
Safari user (Sarah) not able to see images of people on the people page but she can see images on other boxes on other pages...is this across the board for safari...

**Comment by yvonnestruthers** [comment]
I just checked and see the same issue via Safari - I think it's to do with the people template - I'm getting it in the below 2 places: 

http://transitionmovement.org/about-the-movement/the-charity/people/
http://transitionmovement.org/do-transition/training/our-trainers/

I'm on the latest version

![screen shot 2016-11-16 at 14 25 00](https://cloud.githubusercontent.com/assets/10939874/20351225/d9903964-ac09-11e6-83cb-31e8f9cd02f4.png)

@arhinostorm please could you have a look at this one when you've completed the CR items? Thanks!
