### ISSUE TITLE
Trainings appearing in menu under inner transition

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#79]
Hi - Training is appearing as a menu item in do transition/ inner - cannot see it in the menu to delete so this must be a bug.

**Comment by yvonnestruthers** [comment]
![screen shot 2016-11-16 at 15 41 56](https://cloud.githubusercontent.com/assets/10939874/20353572/3d7e1ff0-ac13-11e6-8f4f-44e3fd9c2abc.png)

http://transitionmovement.org/do-transition/training/trainings/

Not sure on this one - the breadcrumb and URL for trainings is correct when you click into it from the menu item under Inner Transition. 

@thisisyoke @arhinostorm please can you advise/fix? 

Thanks
