### ISSUE TITLE
implementing new user list

### ISSUE THREAD

**Issue by yvonnestruthers** [transitionnetwork/TNv3.0#81]
Jay has recommended that we delay on this until after go live.

The reason for this is that last time Jay uploaded, content detached from the authors and he had to work through and re connect - that wasn't a problem before as we were in the build phase, and so had time to work through it all and ensure all was OK before handing over again. But as we are so close to the go live date, this is not a risk we want to introduce at this stage in the project. 

This is simply a 'clean up' job, so it's not imperative to the go live and Jay would be much more comfortable doing this once we have a proper staging area set up, as we currently only have the one version. 

I have booked in for Jay to implement this on the staging area next week, once we have gone live and then once everything is sorted, we can push the new list live. 

So the process will be: 
- Sam to set up seperate live area (hopefully today), which will leave us with the area we are currently working on as the staging site
- Leave the users list as is for go live
- After go live this work to be completed on the staging area first
- Isolate Editor and Admin users which have been set up in the wordpress site to be retained
- Delete all other users from the current user list we have in place
- Then upload the new users xml, the result of this will be to then have all the users that we want on the list 
- Address any authorship issues which emerge on staging
- Then once happy, push to live

**Comment by ainsliebeattie** [comment]
Is this still an issue or is it closed? I am unclear?

**Comment by samuk** [comment]
Unclear what this was about, but if we don't know what the issue is, presumably it's a non-issue.
