### ISSUE TITLE
Stories hero area fileters crossing with text at smaller screen sizes

### ISSUE THREAD

**Issue by yvonnestruthers** [transitionnetwork/TNv3.0#85]
![screen shot 2016-11-21 at 11 14 35](https://cloud.githubusercontent.com/assets/10939874/20480729/b67f1208-afdb-11e6-96d2-f26562ad981b.png)

Stories http://transitionmovement.org/stories/ he above is happening when you reduce the size of the screen. 

Jay sugests to move the filters down into the white space below the hero to rectify this

**Comment by arhinostorm** [comment]
Please note this required  a CSS change so you might need to clear your cache in order to see it.
