### ISSUE TITLE
Increasing depth of resources boxes

### ISSUE THREAD

**Issue by yvonnestruthers** [transitionnetwork/TNv3.0#86]
2 line titles are crossing over with icon at smaller screen sizes

Eg here: 
http://transitionmovement.org/do-transition/starting-transition/7-essential-ingredients/healthy-groups/

![screen shot 2016-11-21 at 11 17 17](https://cloud.githubusercontent.com/assets/10939874/20480842/35b0aa1e-afdc-11e6-89de-970e5528fef3.png)

Please increase the height of the resources listings boxes to be tall enough to handle a 2 line title

**Comment by yvonnestruthers** [comment]
Hey Tom - I'm still getting some of the titles crossing over with the icon 

http://transitionmovement.org/do-transition/starting-transition/7-essential-ingredients/healthy-groups/

![screen shot 2016-11-21 at 15 06 55](https://cloud.githubusercontent.com/assets/10939874/20487672/3bad8624-affc-11e6-8c64-e6b29c603c0f.png)

**Comment by arhinostorm** [comment]
Might need to clear your cache to see changes.

**Comment by yvonnestruthers** [comment]
Yes it's OK now - all other changes I could see oddly - but yes, this is fixed now. Thanks!
