### ISSUE TITLE
Still using Initiatives rather than groups

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#9]
Mike has noted that 
"Throughout the Transition near me section, we are still using Initiatives, should this not be groups?"

Can we do a change all on this one in the support section and make it Groups?

**Comment by yvonnestruthers** [comment]
Just need some clarification on this one - is it that the terminology has changed from initiatives to groups? So in the menu drop down it would be 'Groups' and 'Hubs' and on the map key it would be 'Groups' rather than 'Initiatives'?

**Comment by yvonnestruthers** [comment]
Ainslie to check with Sarah and feedback

**Comment by thisisyoke** [comment]
@ainsliebeattie if you could update this issue with your progress that would be great

**Comment by thisisyoke** [comment]
@ainsliebeattie can you update us on this issue please.

If it is a global change of the term initiative -- into -- groups then this is fairly chunky. We would need to amend:

- the name of the custom post type
- the reference to this custom pot type throughout the code
- The url structure
- the map code

Will estimate this..
