### ISSUE TITLE
our trainings

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#90]
hi - during launch the order of the do transition page changed completely - training was appearing twice, start transition and it's family of pages disappeared and transition in action took the lead in do transition. I have fixed them all now except that our trainings no longer appears on the drop down menu. As this is a hard coded page I cannot change it.  can you fix this please.
cheers

**Comment by arhinostorm** [comment]
Have fixed this. The menu is very specific and doesn't really follow many rules so if you reorder this some of the more bespoke stuff is likely to break.
