### ISSUE TITLE
Install Google Analytics plugin please

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#91]
On REconomy we use 

https://wordpress.org/plugins/google-analyticator/ 

Which seems to do the job

Thanks

Sam

**Comment by yvonnestruthers** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-75130451-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by yvonnestruthers** [comment]
Tom has recommended that we implement GA directly into the code rather than using a plug in to do this. I will come back to you with a time estimate for this to come out of the maintenance time for approval.

**Comment by yvonnestruthers** [comment]
A question following up on my last comment - do you want a plug in because you would like a page to view the GA results from within WP, or are you happy to log in to GA itself to monitor? 

Please let me know and we will act accordingly. 

Many thanks

**Comment by yvonnestruthers** [comment]
Hi @samuk are you able to feed backon my comment above so that we can estimate time needed accordingly? 

Many thanks

**Comment by samuk** [comment]
Having it all integrated together is nice, Ainslie what do you think? 

Would it be good to give Analytics more prominence to authors? It may mean there is a better understanding & visibility of stats across the team?

Thanks

Sam

**Comment by ainsliebeattie** [comment]
Hi Ella - do you have an estimated price yet - we are keen to have it all integrated and ideally capturing stats right now!  Thanks for progressing this urgently.

cheers

**Comment by yvonnestruthers** [comment]
Hi Ainslie - we need feedback on the course of action re the comments above - if you could come back to me on those, I can then get a time estimate for you. 

Many thanks

Ella

**Comment by yvonnestruthers** [comment]
Hi Ainslie and Sam,

I haven't heard back re my comment above, but just so that data is being collected Tom has implemented GA into the code. 

Let me know if you also need a plug in so that you can see GA results via the Wordpress dashboard as well. 

Thanks

Ella 

Time spent: 15 minutes

**Comment by ainsliebeattie** [comment]
sorry Ella - I think we thought we were answering by saying we wanted integration - yes we want a plugin so that we can do it all from inside WP. cheers

**Comment by yvonnestruthers** [comment]
Hi Ainslie - thanks for the confirmation - that's fine we will implement the plug in. https://wordpress.org/plugins/google-analyticator/

I'll get this booked in for next week with the couple of other maintenance items as addressing several things together is much more time (and therefore cost) effective.

**Comment by yvonnestruthers** [comment]
Estimate: 15 minutes

**Comment by yvonnestruthers** [comment]
Hi @samuk 

Please could you supply us with the log in details for your GA account? The plug in asks for these before we can implement the dashboard in Wordpress. 

Many thanks

Ella

**Comment by yvonnestruthers** [comment]
Hi @samuk just chasing up on the comment above - are you able to email these to me plase? 

Many thanks

Ella

**Comment by thisisyoke** [comment]
@samuk or @ainsliebeattie can you send over the login details for your GA account please and we will get the plugin all set up. Happy if you want to send the info via signal, I, Jay, am on signal

**Comment by ainsliebeattie** [comment]
@samuk do you have these details.....
