### ISSUE TITLE
robots.txt edit please

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#93]
Hi could you edit 

https://transitionnetwork.org/robots.txt

To 
User-agent: *
Disallow:

I think this is the best practice now? https://yoast.com/wordpress-robots-txt-example/

Thanks 

Sam

**Comment by samuk** [comment]
Or I'm happy to do it if you can approve me making the change?

**Comment by arhinostorm** [comment]
This has been added.
