### ISSUE TITLE
Additional redirects

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#94]
Just looking through the 404's from today, could you add redirects for

/blogs/feed/rob-hopkins	
/news/feed	
/blogs/feed/rob-hopkins/	
/blogs/feed	
/news

All to https://transitionnetwork.org/news-and-blog/

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi @arhinostorm are you able to add these redirects to the 301s in the htaccess file please? Thanks!

**Comment by samuk** [comment]
Just to add to this, could we have regex that sends

tags/*
to
https://transitionnetwork.org/news-and-blog/
	
events/*
to
https://transitionnetwork.org/do-transition/events/

node/* 
to
https://transitionnetwork.org/

Thanks

Sam

**Comment by arhinostorm** [comment]
Done. 5 mins.
