### ISSUE TITLE
Users unable to register - Captcha not displayed

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#95]
On this page

https://transitionnetwork.org/user-register/

No captcha is displayed, but when the form is submitted it  complains that it was filled incorrectly.

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Just looking into this - will feedback on here ass soon as I have more detail. 

Thanks

Ella

**Comment by arhinostorm** [comment]
fixed.
