### ISSUE TITLE
Confirm Rocket cache is acceptable

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#96]
Hi we're planning to purchase 

https://wp-rocket.me/pricing/

In the next couple of days (to take advantage of black Friday discount)

Can you confirm that you will be happy to install this plugin at a later date?

Details:
http://wpdevshed.com/best-wordpress-cache-plugin/

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

Sorry I'm not sure that I understand the question - do you just need confirmation that the rocket cache plugin referenced in issue 72 is compatible? Or is this an additional plug in to rocket cache that needs installing? 

Many thanks

Ella

**Comment by samuk** [comment]
Hi Ella

More that you're happy with it as a sensible route to installing a cache. The plugin seems good to you in terms of security etc.

The reading I've done suggests it's good. But we don't want to buy something which Tom then isn't happy to install.

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

Thanks for clarifying. 

It looks OK, but it's not a plug in we have used before so we are not able to vouch for it, and we can't be 100% sure before implementing it on the staging area. 

However, we don't have any objection to using it, and will follow the process of implementing on staging, testing on there, submitting to you to test and approve before deploying to live. 

In short, it's fine to purchase it. I'll close this issue and could you put the details into issue 72 once purchased? 

Many thanks
