### ISSUE TITLE
Changing author of Initiatives

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#97]
https://transitionnetwork.org/wp-admin/post.php?post=3189&action=edit

Hi I need to change the author of the above Initiative, to the Author below

https://transitionnetwork.org/wp-admin/user-edit.php?user_id=8572&wp_http_referer=%2Fwp-admin%2Fusers.php%3Fs%3Dian%2Bjackson%26action%3D-1%26new_role%26paged%3D1%26action2%3D-1%26new_role2

How do I do this please?

**Comment by yvonnestruthers** [comment]
Hi Sam,

I've just done this one for you - but the process is as follows: 

- go into the user who needs to become the author 
- change their permission level to be 'contributor' (this is only temporary)
- save the new settings
- go into the relevant initiative and scroll down the spage until you find the 'author' section
- select the person's name from the list 
- save the new settings
- once done, go back to the user who you just made a contributor, and revert them back to being a subscriber (their name still stays as the author once you've done this)
