### ISSUE TITLE
Safari page rendering

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#98]
Using Safari 10 on Yosemite
http://www.whatsmybrowser.org/b/C0HJ1TF

Sarah is reporting only the top bit of the homepage is visible
https://www.dropbox.com/s/4ieb49frwa75s9y/Screenshot%202016-11-24%2011.49.09.png?dl=0

**Comment by yvonnestruthers** [comment]
Hi Sam,

I can't repliate this issue on Safari 10. I wonder if you could ask Sarah to clear her cache and the load the page again and see if that helps? 

Many thanks

Ella

**Comment by arhinostorm** [comment]
I tried last night and around 7pm the server was being really funny. Kept
getting 503 errors. I tried about half an hour later and was fine, so I
suspect teething problems with the server rather than anything to do with
safari.

**Comment by yvonnestruthers** [comment]
Thanks Tom - I'll close this issue for now as it does sound like a server issue. 

Sam - it will be worth keeping an eye on server hiccups and following up with Hetzner if they continue. 

Many thanks

**Comment by samuk** [comment]
More from Sarah on this:

I've just cleared my cache and when I went back into the site all the images showed up.  But when I logged in again, they disappeared!

Just logged out and the homepage was again restored. Does that shed any light?

**Comment by yvonnestruthers** [comment]
I'll get advice from Jay/Tom on Monday on this one for you - I'm still not able to replicate it on live. 

Many thanks

**Comment by arhinostorm** [comment]
I think this was related to issue 100, which I have fixed. The comment you left on here about logging in and logging out was to thank for that. The issues only occurred when you were logged in.

 https://github.com/transitionnetwork/TNv3.0/issues/100
