### ISSUE TITLE
Typo on https://transitionnetwork.org/create-an-initiative/

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#99]
On https://transitionnetwork.org/create-an-initiative/

Please amend

Add you address to the initiatives map, but clicking the button below >

Add you address to the initiatives map, by clicking the button below

**Comment by yvonnestruthers** [comment]
We have fixed the issue but are apprehensive to push it live at the moment becasue the dev area is currently behaving oddly (we suspect server issues) and we do not want to inadvertantly introduce any issues into live. 

Sam - have you submitted the ticket to Hetzner to request SSL on the dev area? 

Many thanks

**Comment by samuk** [comment]
Hi Ella

Yes I've just raised a Hetzner ticket.

I had a look at the server via top

(You can SSH in to ssh -p 222 transk@78.46.5.122 with the password I sent in SMS)

I'm only seeing a load average of 15% CPU whilst running a Wordfence scan, so it seems there is plenty of resource available.

I'll let you know the outcome of the SSL ticket.

Thanks

Sam
